### ISSUE TITLE
Scaling on Medium-Sized Devices

### ISSUE THREAD

**Issue by CharlieCamp98** [gkapfham/www#1]
**Issue:**
When accessing the site on devices with certain (medium) screen widths, the links in the header bar are pushed down below the title, rather than collapsing into a mobile-ready menu. Not only is this detrimental to the cosmetics of the website, but also leads to poor user experience on mobile devices in landscape mode, as the header bar takes up ~33% of the screen height.

**Solution:**
Adjust your CSS media queries such that they appropriately respond to every screen width. These queries should either adjust the size of the text or instantiate a collapsible menu. Since your website utilizes the Twitter Bootstrap framework, you may be able to resolve this issue by checking out the [documentation](http://getbootstrap.com/css/).

**Image:**
![screenshot from 2017-01-20 15-46-44](https://cloud.githubusercontent.com/assets/22163606/22165007/ad6f8762-df27-11e6-918a-ed5eb9e59605.png)

**Comment by vanslykej** [comment]
I also noticed this problem and in the world of ever-changing screen sizes and everyone having a different size, it is important that the tabs at the top correctly and fluidly change into a drop down option instead of awkwardly dropping below your name.

**Comment by gkapfham** [comment]
Hello @CharlieCamp98 and @vanslykej! Thanks for raising this issue. You are correct this is a problem on the header of my site. I would be glad to accept a pull request if you are able to implement a new template that did not exhibit the problem. Also, I would appreciate it if you could share more details about how, specifically, you would suggest that the header should accommodate different screen sizes.

Okay, let's keep the conversation going! You have persuaded me that this needs to be fixed; I have classified it as a bug and marked it with the "help wanted" tag.

**Comment by gkapfham** [comment]
Hello again @CharlieCamp98 and @vanslykej. I have rewritten the code that generates the header and this issue should now be fully resolved. Thanks for reporting it! I will now close this issue. But, if you notice any further problems like this, I hope that you will raise a new issue.
