### ISSUE TITLE
Layout Suggestion

### ISSUE THREAD

**Issue by liux2** [gkapfham/www#11]
Hi,
I have a suggestion for the layout of this website.
I think you there can be individual plates for courses and materials. The current way of sorting the materials is a little hard to read and a little hard to find what we want.

**Comment by liux2** [comment]
More about my suggestion is that the colour and the theme was good. However, the layout can be improved by rearrange it. Different details can be put in different frames. There is an advantage of arrange details by different frames, that is, the layout now is not very consist, different frames can make it clean and consist. The layout now is suitable for reading. Websites like New York Times are very suitable for this layout. Since the main users for this website are students or people who want to search for certain informations, different frames can be helpful. One example is Apple's official website, in this website, different products was arranged in different windows, and that makes us easy to determine what our target is.

**Comment by liux2** [comment]
P.S.
Current page was like curtain news in news website as the picture shows:
![screenshot from 2017-01-23 15-33-18](https://cloud.githubusercontent.com/assets/23517453/22221587/bc668b10-e181-11e6-9688-9eea1bf0b1ec.png)
The website should also consider mobile users. To achieve that, you can simply arraticnge it as frames one followed by one vertically. In computer, it can be like grid-like frames.

**Comment by gkapfham** [comment]
Hello @liux2! Thanks for raising this issue. I can see the value in the more complex layout that you are proposing. However, to ensure that the responsive (i.e., mobile-ready) layout was correct for the proposed type of design would be very difficult. As I recall, the site you mentioned is not mobile-ready, which I would prefer to avoid. As such, I propose to close this issue for now. If you have suggestions for minimal ways in which I could improve the layout, then please comment further on this issue.
