### ISSUE TITLE
 Institute of Applied Information Processing

### ISSUE THREAD

**Issue by zbzoll** [gkapfham/www#13]
When you click on this link, the link brings up a 503 Service Unavailable instead of the link. You should fix this link because it helps you prove your past experiences and how you became an Associated Professor at Allegheny    
![screenshot from 2017-01-23 15-16-09](https://cloud.githubusercontent.com/assets/25254848/22221040/394fad80-e17f-11e6-9b3d-0133648d39bc.png)

![screenshot from 2017-01-23 15-16-16](https://cloud.githubusercontent.com/assets/25254848/22220975/ed2e1c66-e17e-11e6-8ce8-c5919ddd38e9.png)

I found a link to the University of Uulm that you could use. 
http://www.uni-ulm.de/mawi/mawi-ausland/incomings/information/

**Comment by CharlieCamp98** [comment]
I would even recommend using a service such as [SiteImprove](https://siteimprove.com/) in order to find dead links on-the-fly.

**Comment by nadeld** [comment]
To add to this, when left-clicking on many of the links on the website it should open that website in a new tab rather than replacing it.

**Comment by gkapfham** [comment]
Hello @zbzoll, @CharlieCamp98, and @nadeld! I have fixed the broken links that you mentioned and will look into the tool that you suggested. Since this issue is resolved I am going to close it now.
