### ISSUE TITLE
Papers Organization

### ISSUE THREAD

**Issue by geerc** [gkapfham/www#14]
Because there are so many papers, written about many different topics, I would suggest categorizing them by subject rather than year. This would make it much easier for people to find a specific paper, or papers that would interest them.

**Comment by spitalnyd** [comment]
I agree to this because throughout the website their is a lot of similar topics that aren't really grouped together. Because of that it makes it hard to find a specific paper or item that you are trying to find. By grouping similar topics it makes it easier for the student to find certain information.

**Comment by gkapfham** [comment]
Hello @geerc and @spitalnyd! Thanks for raising this issue. I agree that it would be useful if my papers were also organized according to a theme. However, the dominant way to organize a researchers papers is according to the year of publication. While I would also like to organize them by year, I regret that I do not have time to extend the Jekyll-Scholar plugin to make this work. However, I have started writing a blog post that contains articles on certain themes related by my research.

You can find the blog posts at:

http://www.cs.allegheny.edu/sites/gkapfham/blog/

The blogs are organized by categories at this web site:

http://www.cs.allegheny.edu/sites/gkapfham/categories/

Although I recognize that I have not fully resolved this issue, I think that this is the best that I can do given time constraints; as such, I am going to close the issue.
