### ISSUE TITLE
Asset Optimization

### ISSUE THREAD

**Issue by CharlieCamp98** [gkapfham/www#16]
**Issue:**
Your website includes several Javascript and CSS files that are uncompressed. Professionals in the web development industry highly recommended the compression of these files in **production** in order to improve loading times and prevent unnecessary bandwidth usage.

You should consider compressing the following files:

- css/bootstrap.css
- css/bootstrap-slatemod.css
- css/pygments.css
- css/fontello.css
- js/twFetcher.js

**Solution:**
Bootstrap's Javascript library and FontAwesome are already compressed. Use [JScompress](https://jscompress.com/) to compress your Javascript files and this [CSS Minifier](https://jscompress.com/) to reduce the size of your CSS files.

**Comment by gkapfham** [comment]
Hi @CharlieCamp98! Thanks for pointing out this issue. When I have time, I will compress the files so that they are less resource intensive. I will leave open this issue as a reminder. In the short term, perhaps it is worth noting that some of the files are not compressed because I still edit them regularly and I do not have something integrated into the sites build process that will do this for me when I am preparing a production site. Do you know of an easy-to-use tool that I can integrate with Jekyll?

**Comment by CharlieCamp98** [comment]
One solution that I have in mind would be to create a [Gulp](http://gulpjs.com/) task that would compress these files. This is how I would accomplish this:

1. Ensure that NodeJS and NPM are installed on your development environment.
2. Create a package.json file within the /gkapfham directory that includes gulp as a development dependency. (This isn't a requirement but highly recommended.)
3. Create a gulpfile.js file within the /gkapfham directory. This is the file that will contain the script that will actually compress your files. See Gulp's documentation for more information. You will most likely want to use [Gulp-Clean-CSS](https://github.com/scniro/gulp-clean-css) and [Gulp-Minify](https://www.npmjs.com/package/gulp-minify) to compress your CSS/JS files.
4. Run the 'gulp' command and your files will be minified.

This should be 100% compatible with Jekyll, but does require the dependencies mentioned above.

**Comment by gkapfham** [comment]
Hello @CharlieCamp98. I have now fully integrated Gulp into my web site and the deployed assets should now be optimized. Thanks for suggesting this improvement. I am now going to close this issue. But, if you notice that there are lingering assets that are not optimized, please comment further and I will investigate.
