### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by vanslykej** [gkapfham/www#18]
On the biography section of the website, there are two broken links in the first paragraph. The words highlighted in orange which say: "University of Virginia" and "Institute of Applied Information Processing" are links which when clicked on, lead to a "server not found" and "server unavailable" page. I suggest that you fix these links since the rest of the links seem to work and it would be very convenient for users of the site to be able to learn more about, in this case, these two institutions where you have been a visiting research scientist.

**Comment by gkapfham** [comment]
Hello @vanslykej! Thanks for pointing out the mistakes in these links. I have corrected them all and thus I judge this issue to be resolved and worthy of closing. Please let me know if you find any more broken links and I will be glad to fix them as well.
