### ISSUE TITLE
Improvement for Teaching section of the website

### ISSUE THREAD

**Issue by burrowss** [gkapfham/www#2]
Since there are so many courses that you have taught and have on the website, you could consider sorting them in groups by the years they were taught and making these groups collapsible. This would make it more accessible and less cluttered since there would be fewer classes shown but they would still be available. Another solution would be to create groups that are all the same class (eg Computer Science 111) and then sort those groups by the most recent year so that students could find their class quickly.
-Simon Burrows

**Comment by Nikki-Luoma** [comment]
I agree! It seems cluttered to go on the website and see all of the different classes.

**Comment by geerc** [comment]
I agree, this would make it much easier to navigate this part of the website.

**Comment by comptonb37** [comment]
I too agree, this would also be nice for students who have taken classes with you previously who want to reference assignments in other classes and may skip over the class they are looking for a few times because of how similar they all look.

**Comment by cookc3174** [comment]
This was one of the first parts about the website I noticed. Having all the classes on there does make it confusing. I agree that they should be categorized by year.

**Comment by gkapfham** [comment]
Hello everyone! This is a really good point! Right now, the code is not setup to be able to organize the courses by year. But, I like this idea and I will leave it open. When time permits, I will try to rewrite the code that generates the teaching page so that the years are also highlighted. For now, I will keep this issue open as a reminder to add this new feature.

**Comment by gkapfham** [comment]
Hello @burrowss and @Nikki-Luoma and @geerc and @comptonb37 and @cookc3174! Thanks for making this suggestion. I found a way to rewrite the program that generates the HTML for the listing of my courses and implemented the feature that you requested. As such, I am going to close this issue. But, if you notice any problems, please comment here and I will try to resolve them!
