### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by mendezjw** [gkapfham/www#22]
I had a very difficult time finding the contact page when I was trying to resolve my previous issue. I was required to search through multiple pages until I found the contact link on the teaching page. I feel it would be better to list the contact page on the top of the website. It would improve the user's ability to find and access this page as well as showing that the page exists.

**Comment by gkapfham** [comment]
Hello @mendezjw! Thanks for carefully reviewing my site to find this serious mistake. I have resolved the problem in 502ee99. Can you please confirm that I have resolved the issue that you raised? Once you confirm that I have solved this problem correctly, I will go ahead and close it.
