### ISSUE TITLE
quick access to email 

### ISSUE THREAD

**Issue by alcantaram** [gkapfham/www#23]
As I began to surf different links I had difficultly identifying your email. As a proposal, I suggest to edit the main page and insert your email and slack contact next to the social media buttons on the bottom of the page. Setting this adjustment will allow user to find email and slack information other than what  you have provide as a contact method.

**Comment by gkapfham** [comment]
Hello @alcantaram! Thanks for raising this issue. For now, I am going to continue to not explicitly include my email on the web site, so as to ensure that I do not receive many unwanted emails. For now, someone can contact me by visiting the "Contact" page and then using the reCaptcha to reveal my email.
