### ISSUE TITLE
Addition to Research Section

### ISSUE THREAD

**Issue by Mitchello457** [gkapfham/www#5]
While browsing the "Research" section, I noticed that there were no specific examples of the research that you have conducted. I understand that you do not want to be redundant with your information between the "Biography" and "Research" sections. This information is already present in your self-description. I believe that within your "Biography" section, you should be more general and link the "Research" section from this. Your biography should contain general topics and the research page should be more specific. This will make things more clear for the user because when I click on "Research" I can read about the many different things that you have discovered. This is opposed to what is currently present on the site. I find no specifics about your own research except while reading your biography.  Why should I read your biography when I am only interested in the different things that you have researched?

**Comment by myersj451** [comment]
I agree with this improvement as the "Research" page does not contribute much useful information to the website. In addition to the links found in the paragraphs, a concise and/or simple presentation of completed research can improve the content the page provides. Undergraduates and professionals can gain a stronger knowledge of your work more efficiently.

**Comment by taylor-redman** [comment]
I addressed this issue in my post as well. A lot of his research links were either filed under separate tabs or were organized in different sub-sections in the Software section. I agree that there are some organizational tweaks that could be made in order to make his information more easily accessible to the site users

**Comment by gkapfham** [comment]
Hello @Mitchello457, @myersj451, and @taylor-redman! I think that the issue you have raised is a very good one. As such, I have substantially extended the site to include the details you requested. You can find the new version of the site at:

http://www.cs.allegheny.edu/sites/gkapfham/research/

Does this look like what you expected? Again, thanks for raising this issue. I am going to close it now as I judge it to be appropriately resolved. If there are more details that you would like to see, you are welcome to comment further here.
