### ISSUE TITLE
Email Link

### ISSUE THREAD

**Issue by mendezjw** [gkapfham/www#7]
The email on the contact page requires the user to click on a link and authenticate that they are a real person before they can view the email. I feel it would be easier to place the full email on the page without the extra verification step. A change that could be implemented would be to remove the hyperlink and replace it with a clear image of the email. This will remove steps to getting the email and prevent spam.

**Comment by hornbergerc** [comment]
I agree because someone could be in a rush and they need to quickly find the email and they have to perform an extra step.

**Comment by CharlieCamp98** [comment]
I would actually recommend NOT implementing this change. 

This is due to the fact that spam 'bots' or 'scripts' often times parse web pages in search of email addresses to add to spam lists. Human verification prevents this issue entirely.
