### ISSUE TITLE
Missing Highlighted Courses

### ISSUE THREAD

**Issue by Murph45** [gkapfham/www#8]
One issue that I found is that on the home page of the website the link to the "First-year/sophomore 102" course is not found as easy as it should be. As it is a new course initially it was difficult for me to find, thus making it hard to reach the necessary links to follow along in class. While not hard to find after one initially finds it by clicking on the  "Computer Science 111, Spring 2017" and looking at the bottom of the page; it would be nice and more easily accessible if the link would be found under the "Highlighted Courses" heading.
Without having to create a new header for any new courses that you will teacher in the future I would suggest adding in a explanation onto how to find current and or past courses. This explanation could be placed at the top of the page or along the side that quickly talks about how to reach the courses. The explanation could point visitors of the website to the "teaching" banner of the website where all the courses are already listed. You could also change the "Teaching" banner to something simpler to "Classes". This banner gets right to the point and let visitors know that if they are looking for any course, this is the place to go.

**Comment by Nikki-Luoma** [comment]
I agree, on the first day of class it took extra time to navigate to the page we needed.

**Comment by Mitchello457** [comment]
This is an issue that I also found apparent. It took me much longer than it should have to find the correct class because there is no distinction between on going classes and those that have concluded.

**Comment by vanslykej** [comment]
This is a good issue to be resolved. If there was a section for past and current classes it would be much easier to find the desired class you are looking for.

**Comment by alcantaram** [comment]
If resolved, as a frequent user this will allow getting the resources rapidly.

**Comment by gkapfham** [comment]
Hello everyone! Thanks for raising this issue. For now, the model that I am following on the main page of the site is that each header has one line and one line for descriptions. So, if I were to add another course, this would break the pattern that this page follows. While I can certainly see the point that you are making, for now I am going to mark this as an enhancement request and close the issue. I may revisit the issue in the future if I can devise a simple way to include links to multiple courses.
