### ISSUE TITLE
Biography Topic Suggestion

### ISSUE THREAD

**Issue by comptonb37** [gkapfham/www#9]
May I suggest that you consider including some description of your personal life on your biography page? The information on the page was simply about your professional life, which is very important for your website to have, but I'm curious to learn (and am sure others are interested in knowing) more about your family life and maybe some hobbies of yours. I was also quite disappointed at the lack of mention of Bosco, your dog, and would have liked for more people to know about his gracefulness. I would recommend adding this section immediately before the discussion of your professional principles in the classroom so that your biography still ends with that crucial, respectable policy. I understand that this is your professional website, but I think this addition would help your current students and faculty members better relate to you. The section does not need to be very extensive, but substantial information about you and what you like could also possibly attract new students considering studying computer science to take one of your classes; if they look into your website to see if you're a cool professor that they'd like to take a class with, this information may be the difference between them adding the class or looking elsewhere.

**Comment by Nikki-Luoma** [comment]
Although, I would like to learn more about Professor Kapfhammer, adding private and personal information is not the best thing to do when the website is not private.

**Comment by gkapfham** [comment]
Hi @comptonb37! Thanks for raising this issue. For now, I am inclined to agree with @Nikki-Luoma on this issue. I judge that it is most appropriate to keep these details about my dog on sites like Twitter or Instagram. Also, I found your issue to contain a long paragraph that was difficult to read. As such, I am closing this issue. You are welcome to revise your comment or to add a new one if you have new evidence as to why I should add these requested details.
